-- AUTO-GENERATED LAUNCHER FOR LOCAL DEVELOPMENT.
--
-- This file is automatically generated by `npm run setup-resolve` from the
-- template in src-tauri/resources/AutoSubs (Dev).lua. It points Resolve at your
-- local AutoSubs source tree and starts the core server in development mode.
--
-- NO EDITING NEEDED: just run `npm run setup-resolve` from AutoSubs-App/.
-- The copy of this file that lives in your DaVinci Resolve scripts folder is
-- generated from the template in the repo (src-tauri/resources/AutoSubs (Dev).lua)
-- by running, from the AutoSubs-App directory:
--
--     npm run setup-resolve
--
-- That command bakes the absolute path to your local checkout into the line
-- below, so this launcher is fully self-contained: it points Resolve directly
-- at the AutoSubs source tree and starts the core server in development mode.
-- It does NOT require AutoSubs to be installed normally first, and it never
-- loads AutoSubs.lua. Edits to the Lua modules are picked up the next time you
-- run this script from Resolve (no rebuild needed).

---@diagnostic disable: undefined-global
local ffi = ffi

-- `npm run setup-resolve` replaces the placeholder below with the absolute path
-- to the repo's `src-tauri/resources` folder.
local resources_folder = [[__AUTOSUBS_RESOURCES_FOLDER__]]

if resources_folder == "__AUTOSUBS_RESOURCES_FOLDER__" then
    error(
        "'AutoSubs (Dev).lua' has not been generated yet. Run `npm run setup-resolve` " ..
        "from the AutoSubs-App directory to create a configured copy in your " ..
        "DaVinci Resolve scripts folder."
    )
end

-- Resolve 21.1 may hide package/require from Workspace scripts. Use only
-- primitives Resolve still exposes to bootstrap AutoSubs before touching them.
local sep = ffi.os == "Windows" and "\\" or "/"
local function join_path(dir, filename)
    if dir:sub(-1) == sep then
        return dir .. filename
    end
    return dir .. sep .. filename
end

local modules_path = join_path(resources_folder, "modules")
local compat_path = join_path(modules_path, "resolve_compat.lua")
local compat_chunk, compat_err = loadfile(compat_path)
if not compat_chunk then
    error("Could not load AutoSubs Resolve compatibility bootstrap: " .. tostring(compat_err))
end
local compat = compat_chunk()
if type(compat) ~= "table" or type(compat.bootstrap) ~= "function" then
    error("AutoSubs Resolve compatibility bootstrap returned an invalid module")
end
compat.bootstrap(modules_path)

local AutoSubs = require("autosubs_core")
-- No executable path is needed in dev mode: the core server never launches the
-- desktop app while dev mode is enabled (the final argument below).
return AutoSubs:Init("", resources_folder, true)
